### ISSUE TITLE
[FEATURE] Create product service for handling product CRUD logic

### ISSUE THREAD

**Issue by kunaljain0212** [kunaljain0212/Apni-Dukan-Backend#13]
Controllers are used for the sanitization of inputs and services are used for handling the core logic for a particular route. Keeping this in mind the goal is to separate the core logic of each function in product controller ``server/controllers/product.ts`` to a separate file ``product.service.ts`` under ``services`` directory (`server/services/product.service.ts`).

For reference you can check out the below-mentioned repository to get a better understanding of this particular folder structure:
[AASF-Website-Backend](https://github.com/AASF-IIITM/aasf-website-backend)

- [ ] Create getProductById service
- [ ] Create getAllProducts service
- [ ] Create createProduct service
- [ ] Create updateProduct service
- [ ] Create updateInventory service
- [ ] Create getAllUniqueCategories service

**Comment by disha9112** [comment]
I would like to work on this. Could you please assign it?

**Comment by kunaljain0212** [comment]
Sure go ahead @disha9112! 🚀
